apiVersion: v1
kind: Service
metadata:
  labels:
    service: validation
  name: validation
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: validation
#  type: LoadBalancer    
