apiVersion: v1
kind: Service
metadata:
  labels:
    service: validation
  name: validation
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: validation
#  type: LoadBalancer    
